### PR TITLE
Customercontroller

### PR DESCRIPTION
**Pull request by naienko**
# Description
Created Controller and Test files for Customer table of API. Relevant verbs: GET, POST, PUT. DELETE is NOT available. Includes GET one and GET all. Query strings _include=payments and _include=products, as well as search functionality via q=
See Ticket #2 

## Type of change
Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

# Testing Instructions for Change Made

1. Run 
[fill-bangazonapi-tables.txt](https://github.com/nss-day-cohort-30/bangazon-api-maniacal-magpies/files/3173312/fill-bangazonapi-tables.txt) in Azure Data Studio on BLANK tables
2. `git fetch --all`
3. `git checkout customercontroller`
4. Run Test Suite in Visual Studio
5. Review code

# Checklist:
- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by AjeffersonTN — DISMISSED** [review]
All test past 👍

**Review by emmettSchneider — DISMISSED** [review]
Approved. Tests passed upon adding data to database. Test only ran one time.

**Review by emmettSchneider — APPROVED** [review]
Test passed. Approved.

**Review by AjeffersonTN — APPROVED** [review]
GoOd To Go 👍

**Pull request merged**
